# Generated by Django 5.0 on 2023-12-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=256)),
                ('time_upload', models.TimeField(auto_now=True)),
                ('date_upload', models.DateField(auto_now=True)),
                ('file', models.FileField(upload_to='')),
                ('file_url', models.URLField()),
            ],
        ),
    ]
