# Generated by Django 5.0 on 2023-12-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='file',
        ),
        migrations.RemoveField(
            model_name='filemodel',
            name='file_url',
        ),
        migrations.AddField(
            model_name='filemodel',
            name='file_path',
            field=models.CharField(default=None),
            preserve_default=False,
        ),
    ]
